# Generated by Django 5.2.7 on 2025-10-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='tanggal_pengaduan',
            new_name='tanggal_lapor',
        ),
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Induk kependudukan'),
        ),
    ]
